### ISSUE TITLE
Comments from AlexChang

### ISSUE THREAD

**Issue by AlexChang** [yuchenlin/cppstudy#1]
To start with, I have to say your program is fairly impressive and it did spend me some time getting to understand your program. Since I am not familiar with some of the syntax you used in your program, I won't judge.  However, I suppose you should remove the 51st line from your program or the user will know the answer directly.
All in all, well done.

**Comment by yuchenlin** [comment]
Thank you for your correction. ^_^ I forgot to change the 51st line to annotation because I wanted to check if the program is right. I did used many syntax we haven't study about, like functions. I believe that you will love using functions.
